global:
  resolve_timeout: 5m
  # smtp_smarthost: 'smtp.example.com:587'
  # smtp_from: 'alertmanager@noderr.io'
  # smtp_auth_username: 'alertmanager'
  # smtp_auth_password: 'password'

route:
  group_by: ['alertname', 'chain_id']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'team-blockchain-adapters'
  routes:
  - match:
      severity: critical
    receiver: 'team-blockchain-adapters'
    repeat_interval: 1h
  - match:
      severity: warning
    receiver: 'team-blockchain-adapters'
    repeat_interval: 12h

receivers:
- name: 'team-blockchain-adapters'
  # email_configs:
  # - to: 'blockchain-team@noderr.io'
  #   send_resolved: true
  webhook_configs:
  - url: 'http://noderr:3000/api/alerts'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'chain_id'] 