apiVersion: v1
kind: Service
metadata:
  name: noderr-frontend
  namespace: noderr-prod
spec:
  selector:
    app: noderr-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP # Change to LoadBalancer for external access 