apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: noderr-prod

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'noderr-backend'
        metrics_path: /metrics
        static_configs:
          - targets: ['noderr-backend:3000'] 